### ISSUE TITLE
Handle 401 and possible other HTTP error codes/exceptions

### ISSUE THREAD

**Issue by N0rbert** [anenasa/pyppasearch#4]
I have an issue with your great script. See below:

```
$ pyppasearch.py -c bionic -a amd64 cmake
cmake 3.15.4-1ubuntu3ppa1~bionic ppa:hnakamur/cmake Bionic (amd64)
cmake 3.22.6-0ubuntu1~18.04.sav0 ppa:savoury1/build-tools Bionic (amd64)
cmake 3.12.3-3~ubuntu18.04.1~ppa1 ppa:rsjtaylor/cmake-backports Bionic (amd64)
Searching 17/300Traceback (most recent call last):
  File "/home/username/bin/pyppasearch.py", line 75, in <module>
    main()
  File "/home/username/bin/pyppasearch.py", line 66, in main
    packages = repos[i].search(lp, args.codename, args.arch, args.noexact, args.package)
  File "/home/username/bin/pyppasearch.py", line 15, in search
    owner = lp.people[self.user]
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 998, in __getitem__
    shim_resource._ensure_representation()
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 379, in _ensure_representation
    representation = self._root._browser.get(self._wadl_resource)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 441, in get
    response, content = self._request(url, extra_headers=headers)
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 431, in _request
    raise error
lazr.restfulclient.errors.Unauthorized: HTTP Error 401: Unauthorized
Response headers:
---
content-length: 0
content-type: text/plain;charset=utf-8
date: Wed, 14 Sep 2022 08:54:12 GMT
server: gunicorn/19.8.1
status: 401
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: b40c9f14-1093-4f11-961d-447ca4cb3cc6
x-vcs-revision: d1a8db0ec52d1c50071022e2e670bde7beea6c4c
---
Response body:
---
b''
---

```

So it stops on HTTP 401 Error. 

Locally I hacked this by the below patch, 

```
--- /tmp/pyppasearch.py
+++ /home/username/bin/pyppasearch.py
@@ -12,20 +12,23 @@
         self.url = url
 
     def search(self, lp, codename, cpu_arch, noexact, search):
-        owner = lp.people[self.user]
-        archive = owner.getPPAByName(distribution=lp.distributions["ubuntu"], name=self.name)
-        binaries = archive.getPublishedBinaries(status='Published', binary_name=search, exact_match=not noexact)
+        try:
+            owner = lp.people[self.user]
+            archive = owner.getPPAByName(distribution=lp.distributions["ubuntu"], name=self.name)
+            binaries = archive.getPublishedBinaries(status='Published', binary_name=search, exact_match=not noexact)
 
-        packages = []
-        if len(binaries) > 0:
-            for binary in binaries:
-                distro_arch_series = binary.distro_arch_series_link
-                binary_codename = distro_arch_series.split('/')[-2]
-                binary_arch = distro_arch_series.split('/')[-1]
-                if (codename is None or codename.lower() == binary_codename) and (cpu_arch is None or cpu_arch == binary_arch):
-                    packages.append(Package(self.user, self.name, binary.binary_package_name, binary.binary_package_version, binary_codename, binary_arch))
-        return packages
+            packages = []
+            if len(binaries) > 0:
+                for binary in binaries:
+                    distro_arch_series = binary.distro_arch_series_link
+                    binary_codename = distro_arch_series.split('/')[-2]
+                    binary_arch = distro_arch_series.split('/')[-1]
+                    if (codename is None or codename.lower() == binary_codename) and (cpu_arch is None or cpu_arch == binary_arch):
+                        packages.append(Package(self.user, self.name, binary.binary_package_name, binary.binary_package_version, binary_codename, binary_arch))
+            return packages
 
+        except:
+            return []
 
 class Package:
     def __init__(self, user, repo, name, version, series, arch):

```

but you can do this in other way.

**Comment by anenasa** [comment]
The href of a result from searching ppa is empty, so an error happens.
I fix this with https://github.com/anenasa/pyppasearch/commit/e1595d0e37e9c5b838a1e9f321e6e045c9b28a89. I will leave this issue open until HTTP error handling is implemented.
